### ISSUE TITLE
numerotation not applied

### ISSUE THREAD

**Issue by Strong-Ari** [Scynes/textlight#3]
when I export image the numerotation is not applied
![text example](https://github.com/user-attachments/assets/b7fef03e-afb1-470c-a387-d9f08813333f)

**Comment by Scynes** [comment]
@Strong-Ari thank you for posting this!

What browser were you using when you encountered this issue? This was a known problem I had when I was using Opera.

**Comment by Scynes** [comment]
This bug has been fixed in the latest version of main.
